[package]
name = "league-svc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.6.0", features = [ "runtime-tokio-rustls", "mysql", "chrono", "decimal" ] }
actix-web = "4"
chrono = { version = "0.4", features = [ "serde" ] }
reqwest = "0.11.11"
openssl = { version = "0.10", features = ["vendored"] }